[repository]
name = "Hypr-GlassWindow"
authors = ["sashavrg"]
commit_pins = [
    # [Hyprland commit, Hypr-GlassWindow commit]
    # ["<hyprland_commit>", "<plugin_commit>"]
]

[Hypr-GlassWindow]
description = "A glass shader window effect plugin for Hyprland"
authors = ["sashavrg"]
output = "build/lib/glasswindow.so"
build = [
    "cmake -Bbuild -H.",
    "cmake --build build"
] 